Repository Codeit-Sprint-6-Part-2-Team-9/frontend, pull requests merged in 2024-05, with the labels that each got.

#22 feat: 공용 헤더 컴포넌트 추가#10
  src/App.jsx
  src/assets/logo.svg
  src/assets/myProfile.png
  src/components/Layout/Header.jsx
  src/components/Layout/Header.module.css
Labels: ✨ Feature

#23 Feat/공용라운드프로필컴포넌트#11
  src/App.jsx
  src/components/RoundCard.jsx
  src/components/RoundCard.module.css
  src/components/amber.png
  src/pages/HomePage.jsx
Labels: ✨ Feature

#27 Feat/공용 버튼 컴포넌트 #8
  .gitignore
  package-lock.json
  package.json
  src/App.jsx
  src/assets/Chart.svg
  src/assets/credit.svg
  src/assets/mycredit.svg
  src/assets/plus.svg
  src/components/Buttons.jsx
  src/components/Buttons.module.css
  src/components/Typography.jsx
  src/main.jsx
  src/pages/HomePage.jsx
  yarn.lock
Labels: ✨ Feature

#28 Feat/이달의차트직사각형컴포넌트
  src/components/ChartCard.jsx
  src/components/ChartCard.module.css
Labels: ✨ Feature

#29 faet: 캐러셀카드컴포넌트#17
  src/assets/coverDonation.svg
  src/assets/creditIcon.svg
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.module.css
  src/components/Carousel/CarouselCard.jsx
  src/components/Carousel/donationMockData.json
  src/pages/List.jsx
  src/utils/calculateTimeRemaining.jsx
Labels: ✨ Feature

#35 Chore: prettier 추가 #33
  .eslintrc.cjs
  .prettierignore
  .prettierrc
  package.json
  yarn.lock
Labels: 작업 완료, 📦 Chore

#34 Feat: 모달 컴포넌트 #9
  src/assets/credit_warn.svg
  src/assets/modal_credit.svg
  src/components/Buttons.jsx
  src/components/Modal/CreditChargeModalBody.jsx
  src/components/Modal/CreditChargeModalBody.module.css
  src/components/Modal/CreditDonationModalBody.jsx
  src/components/Modal/CreditDonationModalBody.module.css
  src/components/Modal/CreditWarnModalBody.jsx
  src/components/Modal/CreditWarnModalBody.module.css
  src/components/Modal/ModalComponent.jsx
  src/components/Modal/ModalComponent.module.css
  src/pages/List.jsx
Labels: 진행 중, ✨ Feature

#36 Feat/공용버튼컴포넌트#8
  .gitignore
  src/App.module.css
  src/components/Buttons.jsx
  src/components/Buttons.module.css
Labels: ✨ Feature

#45 Feat: Layout 추가 및 Routing 수정
  src/App.jsx
  src/App.module.css
  src/assets/top_overlay.svg
  src/components/Buttons.jsx
  src/components/Layout/Layout.jsx
  src/main.jsx
Labels: ✨ Feature

#50 fix: App.jsx class 오타 수정 및 오버레이 width 설정
  src/App.jsx
  src/App.module.css
Labels: 🚑 Hotfix

#48 Feat/내크레딧충전하기버튼
  package-lock.json
  src/components/Buttons.module.css
  src/components/MyCreditRechargeButton.jsx
  src/components/MyCreditRechargeButton.module.css
  src/pages/List.jsx
Labels: ✨ Feature

#53 feat: LocalStorage API를 활용한 선호하는 아이돌 정보 관리 기능 구현 (#52)
  src/api/config.js
  src/api/favoriteIdols/FavoriteIdolsExample.jsx
  src/api/favoriteIdols/useFavoriteIdols.js
Labels: ✨ Feature

#60 Fix: RoundCard 컴포넌트 수정 및 index.css에 Reset CSS 추가, 배경색 지정
  index.css
  index.html
  src/components/RoundCard.jsx
  src/components/RoundCard.module.css
  src/pages/List.jsx
Labels: 🚑 Hotfix

#43 Feat: 캐러셀컴포넌트#16
  package.json
  src/App.module.css
  src/assets/btnArrowLeft.svg
  src/assets/btnArrowRight.svg
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.module.css
  src/components/Carousel/CarouselCard.jsx
  src/pages/List.jsx
  yarn.lock
Labels: 진행 중, ✨ Feature

#57 Feat: 캐러셀 카드 컴포넌트에 버튼, 모달 추가#55
  src/api/charts/ChartQueryExample.jsx
  src/components/Carousel/Carousel.module.css
  src/components/Carousel/CarouselCard.jsx
  src/pages/List.jsx
Labels: ✨ Feature

#62 Feat: 캐러셀 컴포넌트에 getDonations 추가#16
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.module.css
  src/components/Carousel/CarouselCard.jsx
Labels: ✨ Feature

#71 Feat/루트랜딩페이지
  src/App.jsx
  src/api/config.js
  src/assets/Img_web_01.svg
  src/assets/Img_web_02.svg
  src/assets/Img_web_03.svg
  src/assets/donatemobile.svg
  src/assets/introimg.svg
  src/assets/mypagemobile.svg
  src/assets/votemobile.svg
  src/components/Buttons.module.css
  src/components/MyCreditRechargeButton.jsx
  src/pages/HomePage.jsx
  src/pages/List.jsx
  src/pages/homepage/Container.jsx
  src/pages/homepage/Container.module.css
  src/pages/homepage/HomePage.jsx
  src/pages/homepage/HomePage.module.css
Labels: ✨ Feature

#74 Fix/랜딩페이지 모바일 반응형 수정
  src/pages/homepage/HomePage.module.css
Labels: 🚑 Hotfix

#79 Feat: 크레딧 충전, 후원하기, 차트 투표하기 모달
  src/components/Carousel/CarouselCard.jsx
  src/components/Modal/CreditChargeModalBody.jsx
  src/components/Modal/CreditChargeModalBody.module.css
  src/components/Modal/CreditDonationModalBody.jsx
  src/components/Modal/CreditDonationModalBody.module.css
  src/components/Modal/CreditWarnModalBody.jsx
  src/components/Modal/CreditWarnModalBody.module.css
  src/components/Modal/ModalComponent.jsx
  src/components/Modal/VoteModalBody.jsx
  src/components/Modal/VoteModalBody.module.css
  src/pages/ListPage/ChartSection.jsx
  src/pages/homepage/HomePage.jsx
Labels: 진행 중, ✨ Feature

#44 feat: 깃허브 액션을 통한 자동 빌드 밎 배포 구현
  .github/workflow/deploy.yml
  vite.config.js
Labels: 진행 중, 📦 Chore

#81 📦 Chore: 잘못된 깃허브 액션 스크립트의 폴더 이름 정정 (#44)
  .github/workflows/deploy.yml
Labels: 📦 Chore

#78 Update README.md
  README.md
Labels: 진행 중, 📚 Docs

#84 🚑 Hotfix : API 클라이언트가 첫번째 페이지의 내용만을 읽어들이는 버그 수정
  src/api/hooks.js
Labels: 🚑 Hotfix

#86 ✨ feat: API클라이언트 기능 보강 (#14)
  src/api/charts/getCharts.js
  src/api/charts/useChartQuery.js
  src/api/config.js
  src/api/donations/getDonations.js
  src/api/donations/putContribute.js
  src/api/donations/useDonationMutation.js
  src/api/donations/useDonationQuery.js
  src/api/hooks.js
  src/api/idols/getIdols.js
  src/api/idols/useIdolsQuery.js
  src/api/utils.js
  src/api/votes/postVote.js
  src/api/votes/useVoteMutation.js
  src/components/Modal/VoteModalBody.jsx
  src/pages/ListPage/ChartSection.jsx
  src/pages/my-page/MyPage.jsx
  vite.config.js
Labels: bug, enhancement, 작업 완료, 🔨 Refactor, ✨ Feature

#88 ✨ feat: CI/CD 구현을 위한 개발, 배포용 설정 분리(#39)
  .env
  .env.development
  .env.production
  index.html
  package.json
  src/App.jsx
  src/api/config.js
  vite.config.js
  yarn.lock
Labels: 작업 완료, 📦 Chore

#90 📦 Chore: 사용되지 않는 파일 삭제(#14)
  src/api/hooks.js
Labels: 작업 완료, 👨🏻‍💻 ETC

#93 Refactor/캐러셀컴포넌트#66
  package.json
  src/api/donations/getDonations.js
  src/api/idols/getIdols.js
  src/components/Carousel/Carousel.jsx
  src/components/Carousel/Carousel.module.css
  src/components/Carousel/CarouselCard.jsx
  src/components/Skeletons/CarouselSlideSkeleton.jsx
  src/components/Skeletons/ChartCardSkeleton.jsx
  src/components/Skeletons/ChartCardSkeleton.module.css
  src/pages/ListPage/ChartSection.jsx
  src/pages/ListPage/List.jsx
  src/pages/ListPage/ListPage.module.css
  src/theme.js
  src/utils/fotmatTargetDonation.jsx
  yarn.lock
Labels: 진행 중, 🔨 Refactor, ✨ Feature

#97 Feat: MyPage 스켈레톤 UI 적용
  src/components/Skeletons/AddFavoriteIdolsSkeleton.jsx
  src/components/Skeletons/AddFavoriteIdolsSkeleton.module.css
  src/components/Skeletons/FavoriteIdolSkeleton.jsx
  src/components/Skeletons/FavoriteIdolSkeleton.module.css
  src/pages/my-page/MyPage.jsx
  src/pages/my-page/MyPage.module.css
  src/pages/my-page/components/EmptyFavoriteIdols.module.css
  src/pages/my-page/components/RoundCardWithText.module.css
Labels: 작업 완료, ✨ Feature

#98 Feat: 메타 태그 오픈그래프 추가 #95
  index.html
  ogimg.png
Labels: 작업 완료, ✨ Feature

#99 🚑 Hotfix: 메인 페이지 이외의 페이지들이 제대로 출력되지 않던 문제 해결(#39)
  package.json
  public/404.html
  vite.config.js
  yarn.lock
Labels: 🚑 Hotfix

#103 🚑 Hotfix: yarn.lock의 문제로 빌드가 실행되지 않는 문제 해결(#39)
  yarn.lock
Labels: 작업 완료, 🚑 Hotfix

#104 🚑 Hotfix: 99번 PR에서 누락된 주소 변경 로직 반영(#44)
  index.html
Labels: bug, 작업 완료, 🚑 Hotfix

#107 🚑 Fix: Header.jsx 로고 Link 추가 (#105)
  src/components/Layout/Header.jsx
Labels: ✨ Feature

#112 ✨ Feat: 투표하기 모달 스켈레톤 추가 (#9)
  src/assets/arrow-left-icon.svg
  src/assets/arrow-left.svg
  src/components/Modal/ModalComponent.jsx
  src/components/Modal/ModalComponent.module.css
  src/components/Modal/VoteModalBody.jsx
  src/components/Modal/VoteModalBody.module.css
  src/components/Skeletons/VoteModalSkeleton.jsx
  src/components/Skeletons/VoteModalSkeleton.module.css
Labels: ✨ Feature

#113 🚑 Fix: Mypage 모바일 반응형 수정 (#32)
  src/pages/my-page/MyPage.module.css
Labels: 🚑 Hotfix

#119 fix: MyPage 반응형 CSS 파일 수정 #32
  src/pages/my-page/components/DeleteBtn.module.css
Labels: 🚑 Hotfix

#121 fix: MyPage CSS 조정 #32
  src/pages/my-page/components/DeleteBtn.jsx
  src/pages/my-page/components/DeleteBtn.module.css
Labels: 🚑 Hotfix
